Er 107 feat/modal common component
eRentronic/eRentronic-Client pull request #75
Opened 2022-11-09 06:59 UTC by herrakam

## PR 타입 (복수 선택 가능)
- [x] 구현 사항
- [ ] 버그 수정
- [ ] 환경 설정
- [ ] 리팩토링
- [ ] 기타

## 주요 작업
- 마크업 작업
- 주요 로직 구현
- 스토리 작성
- 기존 코드에 적용

## 구현 계획
- 기존 모달을 완벽히 대체할 수 있는가?
- 어떤 props를 받아야 할 것인가
- 재사용성을 향상시키기 위해 어떤 걸 고민해야 하는가
를 고민했습니다.

## 데모
스토리북으로 확인

## 코드 리뷰어 에게
* 스토리북 코드는 작성해 놓았지만, 아직 recoil 부분 세팅이 되어있지 않아 에러가 발생합니다. recoil을 적용하지 않았을 때에 잘 작동하는 걸 확인했습니다!!
* dimmed의 음영을 option으로 받을까 고민했었는데, 조절해야 할 경우가 발생하지 않을 것 같아 일단 빼놨습니다. 혹시 추가적으로 props로 받으면 좋겠다 하는 내용이 있으실까요?

2022-11-09 08:26 UTC, godhyeongman commented on src/components/common/Modal/Modal.stories.tsx
> +} as ComponentMeta<typeof Modal>;
argTypes 한번 확인해보시면 재밌는 기능이 많습니다. 인디케이터를 변경할 수 도 있어요 저는 좀 편하게 보려고 몇개 바꾸기도 하고 그랬습니다.

2022-11-09 08:26 UTC, godhyeongman commented on src/components/common/Modal/Modal.stories.tsx
> +};
이부분은 스토리로 필요가 없을것 같네요

2022-11-09 08:30 UTC, godhyeongman commented on src/components/common/Modal/Modal.tsx
> +
e.stopPropagation이 dimmed에 적용된 이유가 있을까요?
position이 fixed 였던걸로 기억을하는데 더 상위가 없을 것 같아서요

2022-11-09 08:31 UTC, godhyeongman commented on src/components/common/Modal/Modal.tsx
> +  };
이부분도 처리하신 이유가 궁금하네요. 이벤트 클릭 전파가 이루어져서 모달이 자동 동작을 안햇나요?

2022-11-09 08:31 UTC, godhyeongman commented on src/components/common/Modal/Modal.tsx
> +`;
스타일 파일 분리하면 좋을것 같네용. 저도 이번에 정리 하려구요

2022-11-09 08:37 UTC, godhyeongman commented on src/components/server/ProductDetail/OrderForm/index.tsx
> +  const [isOptionDisplay, setIsOptionDisplay] = useState(false);
저번에 제가 모달상태 리코일로 사용하면 안될것 같다한게 이부분 때문인데요. 다시보니 여기선 모달 상태가 리코일로 관리되선 안될것 같아요. 지금 사용예시 보면 Modal에게 props를 전달하면 되잖아요? 그리고 하나의 리코일 atom을 공유하고 있기 때문에 여러 모달이 동시에 작동을 하는 문제가 생깁니다. 각자의 모달은 각자의 고유한 상태를 지니고 있으면 좋을것 같아용! 그리고 프롭스 드릴링 문제도 없을것 같구요!

2022-11-09 08:40 UTC, godhyeongman requested changes
리코일 사용처에서 버그가 생길 우려가 있어서 RequestChange를 걸어 놓겠습니다. 그리고 모달에서 Layout의 Core인 Container를 사용할 예정이라 들었는데 적용이 안되있어서요. 이러면 사용할 때마다 Container를 사용해서 불편하기 때문에, 모달에 포함시켜서 개발하는걸로 논의 됬던걸로 기억하는데 이유가 있을까요??

2022-11-09 11:53 UTC, herrakam commented on src/components/common/Modal/Modal.tsx
> +
이부분 관련된 내용은 저희 지라 트러블슈팅 9/10일자 정리를 해놓았습니다!!

2022-11-09 11:53 UTC, herrakam commented on src/components/common/Modal/Modal.tsx
> +  };
이부분도 같이 엮어서 지라에 정리를 해놨어요! 그부분 보시면 이해하실 수 있을 것 같습니다

2022-11-09 13:03 UTC, herrakam commented on src/components/common/Modal/Modal.stories.tsx
> +};
음 그렇네요 테스트 내용 인 거 같아요 지우는게 맞는거 같습니다!

2022-11-09 13:12 UTC, herrakam commented on src/components/server/ProductDetail/OrderForm/index.tsx
> +  const [isOptionDisplay, setIsOptionDisplay] = useState(false);
여러 모달에 동시에 작동을 하는 문제가 발생하겠네요 그렇다고 매번 고유한 아톰을 만들기도 힘들 것 같고, state와 dispatch를 전달받는 방향으로 바꿔봐야겠네요. 프롭스 드릴링 문제는 저희 로직들을 상위 컴포넌트에게 전달받는 저희 컨벤션 상 어쩔 수 없게 발생하는 문제인 거 같아요. 일단 이부분은 제가 고치고 pr을 merge하겠습니다!

2022-11-09 13:16 UTC, herrakam commented
Container를 적용 하려 했는데, container에게 고유한 props를 전달할 수 있나라는 문제가 발생해서 일단 적용은 안했습니다! 지금 모달에서는 isClicked와 onClick을 받을 수 있어야 하는데, 이걸 container 컴포넌트에게 전달할 수 있을까요? 이부분을 pr 날릴때 적어뒀어야 했는데 까먹었네요 ㅠ

2022-11-10 07:41 UTC, godhyeongman commented on src/components/server/ProductDetail/OrderForm/index.tsx
> +  const [isOptionDisplay, setIsOptionDisplay] = useState(false);
이 부분은 discussion으로 논의되어 해결 되었습니다~

2022-11-10 07:42 UTC, godhyeongman commented
> Container를 적용 하려 했는데, container에게 고유한 props를 전달할 수 있나라는 문제가 발생해서 일단 적용은 안했습니다! 지금 모달에서는 isClicked와 onClick을 받을 수 있어야 하는데, 이걸 container 컴포넌트에게 전달할 수 있을까요? 이부분을 pr 날릴때 적어뒀어야 했는데 까먹었네요 ㅠ

---

주간 회의에 적용 방법 전달해서 논의 끝났습니다~

2022-11-13 07:26 UTC, merged